# github actions versions need updating periodically
# for the latest versions see: https://github.com/docker/build-push-action

name: Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Remove unnecessary files
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Check for modifications
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            ebirdst:
              - 'ebirdst/**'
            tidyverse:
              - 'tidyverse/**'
            geospatial:
              - 'geospatial/**'
            dockerst:
              - 'dockerst/**'
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # ebirdst
      - name: Build and push tidyverse image
        if: steps.filter.outputs.ebirdst == 'true'
        uses: docker/build-push-action@v6
        with:
          context: ./ebirdst
          file: ./ebirdst/Dockerfile
          push: true
          tags: ebirdst/ebirdst:latest
      
      # tidyverse
      - name: Build and push tidyverse image
        if: steps.filter.outputs.tidyverse == 'true'
        uses: docker/build-push-action@v6
        with:
          context: ./tidyverse
          file: ./tidyverse/Dockerfile
          push: true
          tags: ebirdst/tidyverse:latest
          
      # geospatial
      - name: Build and push geospatial image
        if: steps.filter.outputs.tidyverse == 'true' || steps.filter.outputs.geospatial == 'true'
        uses: docker/build-push-action@v6
        with:
          context: ./geospatial
          file: ./geospatial/Dockerfile
          push: true
          tags: ebirdst/geospatial:latest
          
      # dockerst
      - name: Build and push dockerst image
        if: steps.filter.outputs.tidyverse == 'true' || steps.filter.outputs.geospatial == 'true' || steps.filter.outputs.dockerst == 'true'
        uses: docker/build-push-action@v6
        with:
          context: ./dockerst
          file: ./dockerst/Dockerfile
          push: true
          tags: ebirdst/dockerst:latest
