# github actions versions need updating periodically
# for the latest versions see: https://github.com/docker/build-push-action

name: Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # tidyverse
      - name: Build and push tidyverse image
        uses: docker/build-push-action@v4
        with:
          context: ./tidyverse
          file: ./tidyverse/Dockerfile
          push: true
          tags: mstrimas/tidyverse:latest
          
      # geospatial
      - name: Build and push geospatial image
        uses: docker/build-push-action@v4
        with:
          context: ./geospatial
          file: ./geospatial/Dockerfile
          push: true
          tags: mstrimas/geospatial:latest
          
      # dockerst
      - name: Build and push dockerst image
        uses: docker/build-push-action@v4
        with:
          context: ./dockerst
          file: ./dockerst/Dockerfile
          push: true
          tags: mstrimas/dockerst:latest
