name: Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # tidyverse
      - name: Build and push tidyverse image
        uses: docker/build-push-action@v2
        with:
          context: tidyverse/
          push: true
          tags: user/tidyverse:latest
          
      # geospatial
      - name: Build and push geospatial image
        uses: docker/build-push-action@v2
        with:
          context: geospatial/
          push: true
          tags: user/geospatial:latest
          
      # ebirdst
      - name: Build and push ebirdst image
        uses: docker/build-push-action@v2
        with:
          context: ebirdst/
          push: true
          tags: user/ebirdst:latest
